server:
  port: 8888

encrypt:
  key: APODNU3093r2rbjzxcn09u213asdhy08WRFH

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        encrypt:
          enabled: true
        git:
          uri: https://github.com/suongisme/microservice-udemy.git
          clone-on-start: true
          default-label: master
          search-paths: my-code/microservices/configs/{application}/

eureka:
  instance:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'